# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YOUTUBE2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        MainWindow.setMaximumSize(QtCore.QSize(600, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ikon/Adsız3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.249, y1:0.091, x2:1, y2:0, stop:0.109453 rgba(161, 5, 7, 215), stop:0.597015 rgba(0, 0, 0, 209));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 100, 521, 271))
        self.groupBox.setStyleSheet("#groupBox{\n"
"background-color: rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.949876, y1:0.341, x2:0.786458, y2:0.159, stop:0.039801 rgba(0, 0, 0, 206), stop:1 rgba(93, 0, 0, 218));\n"
"border-radius:14px;}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.push_indir = QtWidgets.QPushButton(self.groupBox)
        self.push_indir.setGeometry(QtCore.QRect(360, 70, 91, 41))
        self.push_indir.setStyleSheet("background-color: rgb(176, 176, 176);\n"
"border-radius:14px;")
        self.push_indir.setIcon(icon)
        self.push_indir.setIconSize(QtCore.QSize(39, 40))
        self.push_indir.setObjectName("push_indir")
        self.label_Link = QtWidgets.QLabel(self.groupBox)
        self.label_Link.setGeometry(QtCore.QRect(30, 75, 71, 31))
        self.label_Link.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Link.setObjectName("label_Link")
        self.link_yeri = QtWidgets.QLineEdit(self.groupBox)
        self.link_yeri.setGeometry(QtCore.QRect(100, 80, 241, 22))
        self.link_yeri.setObjectName("link_yeri")
        self.label_linkbekleniyor1 = QtWidgets.QLabel(self.groupBox)
        self.label_linkbekleniyor1.setGeometry(QtCore.QRect(290, 140, 211, 31))
        self.label_linkbekleniyor1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.144398, y1:1, x2:0.9249, y2:0.062, stop:0.169154 rgba(161, 5, 7, 215), stop:0.587065 rgba(0, 0, 0, 209), stop:0.776119 rgba(255, 255, 255, 155));\n"
"border-radius:10px;")
        self.label_linkbekleniyor1.setObjectName("label_linkbekleniyor1")
        self.label_linkbekleniyor2 = QtWidgets.QLabel(self.groupBox)
        self.label_linkbekleniyor2.setGeometry(QtCore.QRect(100, 140, 181, 31))
        self.label_linkbekleniyor2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.144398, y1:1, x2:0.9249, y2:0.062, stop:0.169154 rgba(161, 5, 7, 215), stop:0.587065 rgba(0, 0, 0, 209), stop:0.776119 rgba(255, 255, 255, 155));\n"
"border-radius:10px;")
        self.label_linkbekleniyor2.setObjectName("label_linkbekleniyor2")
        self.label_durum = QtWidgets.QLabel(self.groupBox)
        self.label_durum.setGeometry(QtCore.QRect(10, 140, 91, 31))
        self.label_durum.setObjectName("label_durum")
        self.push_indirilenler = QtWidgets.QPushButton(self.groupBox)
        self.push_indirilenler.setGeometry(QtCore.QRect(310, 190, 41, 31))
        self.push_indirilenler.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ikon/icons8-download-material-rounded-70.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_indirilenler.setIcon(icon1)
        self.push_indirilenler.setIconSize(QtCore.QSize(20, 20))
        self.push_indirilenler.setObjectName("push_indirilenler")
        self.label_indirlenler = QtWidgets.QLabel(self.groupBox)
        self.label_indirlenler.setGeometry(QtCore.QRect(140, 190, 161, 31))
        self.label_indirlenler.setObjectName("label_indirlenler")
        self.push_kapat = QtWidgets.QPushButton(self.groupBox)
        self.push_kapat.setGeometry(QtCore.QRect(440, 190, 51, 41))
        self.push_kapat.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.push_kapat.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ikon/kapat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_kapat.setIcon(icon2)
        self.push_kapat.setIconSize(QtCore.QSize(35, 35))
        self.push_kapat.setObjectName("push_kapat")
        self.push_yenile = QtWidgets.QPushButton(self.groupBox)
        self.push_yenile.setGeometry(QtCore.QRect(380, 190, 51, 41))
        self.push_yenile.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.push_yenile.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ikon/yenidenbaşlat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_yenile.setIcon(icon3)
        self.push_yenile.setIconSize(QtCore.QSize(35, 35))
        self.push_yenile.setObjectName("push_yenile")
        self.labelhataresim = QtWidgets.QLabel(self.groupBox)
        self.labelhataresim.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.labelhataresim.setStyleSheet("border-image: url(:/ikon/hata.png);")
        self.labelhataresim.setText("")
        self.labelhataresim.setObjectName("labelhataresim")
        self.label_hatayazi = QtWidgets.QLabel(self.groupBox)
        self.label_hatayazi.setGeometry(QtCore.QRect(60, 20, 151, 16))
        self.label_hatayazi.setObjectName("label_hatayazi")
        self.label_baslik = QtWidgets.QLabel(self.centralwidget)
        self.label_baslik.setGeometry(QtCore.QRect(210, 40, 371, 51))
        self.label_baslik.setObjectName("label_baslik")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sam&Angel"))
        self.push_indir.setText(_translate("MainWindow", "İndir"))
        self.label_Link.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Link:</span></p></body></html>"))
        self.label_linkbekleniyor1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt; font-weight:600; color:#dfd2d3;\">LİNK BEKLENİYOR..</span></p></body></html>"))
        self.label_linkbekleniyor2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt; font-weight:600; color:#dfd2d3;\">LİNK BEKLENİYOR..</span></p></body></html>"))
        self.label_durum.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">DURUM:</span></p></body></html>"))
        self.label_indirlenler.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">İNDİRİLENLER:</span></p></body></html>"))
        self.label_hatayazi.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\"></span></p></body></html>"))
        self.label_baslik.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#dfd2d3;\">Sam&Angel</span></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
